// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyzZxnfUIJADUFNviNoh2mMAiuSDxhMwk',
    appId: '1:331719151756:web:c932e1f57fb4a8294deba9',
    messagingSenderId: '331719151756',
    projectId: 'nike-eancbyt',
    authDomain: 'nike-eancbyt.firebaseapp.com',
    storageBucket: 'nike-eancbyt.firebasestorage.app',
    measurementId: 'G-0Q9HZC992F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_be7JNX1PeOW0omA5bze-9NxSx6nB5XY',
    appId: '1:331719151756:android:64e8a854b647e1804deba9',
    messagingSenderId: '331719151756',
    projectId: 'nike-eancbyt',
    storageBucket: 'nike-eancbyt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_7UP4cbIKD7d3jsWB_1G2oQpgSTfKYs',
    appId: '1:331719151756:ios:0bc237b1f96e18b34deba9',
    messagingSenderId: '331719151756',
    projectId: 'nike-eancbyt',
    storageBucket: 'nike-eancbyt.firebasestorage.app',
    iosBundleId: 'com.example.nike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_7UP4cbIKD7d3jsWB_1G2oQpgSTfKYs',
    appId: '1:331719151756:ios:0bc237b1f96e18b34deba9',
    messagingSenderId: '331719151756',
    projectId: 'nike-eancbyt',
    storageBucket: 'nike-eancbyt.firebasestorage.app',
    iosBundleId: 'com.example.nike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyzZxnfUIJADUFNviNoh2mMAiuSDxhMwk',
    appId: '1:331719151756:web:4f015efee70db6fe4deba9',
    messagingSenderId: '331719151756',
    projectId: 'nike-eancbyt',
    authDomain: 'nike-eancbyt.firebaseapp.com',
    storageBucket: 'nike-eancbyt.firebasestorage.app',
    measurementId: 'G-DZFL98RSF5',
  );
}
